trainer:
  gpus: 1
  max_epochs: 1
  
logger:
  save_dir: ..\training

checkpoint:
  monitor: val/loss/total
  save_top_k: 1
  save_last: true

defaults:
  - model: age_gender_net
  - dataset: uktface