trainer:
  gpus: 1
  max_epochs: 1
  
logger:
  save_dir: D:\\projects\\ulta\\training

checkpoint:
  monitor: val/loss/total
  save_top_k: 1
  save_last: true

hydra:
  output_subdir: Null
  run:
    dir: .

defaults:
  - model: age_gender_net
  - dataset: utkface
  - hydra/job_logging: disabled